import history from '@/assets/subjects/tarix.jpg';
import geography from '@/assets/subjects/geografiya.jpg';
import medicine from '@/assets/subjects/tibbiyot.jpg';
import biology from '@/assets/subjects/biologiya.jpg';
import math from '@/assets/subjects/matematika.jpg';
import english from '@/assets/subjects/ingliz-tili.jpg';
import russian from '@/assets/subjects/rus-tili.jpg';
import chemistry from '@/assets/subjects/kimyo.jpg';

export const subjects = [
 {slug:'tarix',name:'Tarix',description:'O‘tmishdan saboqlar, kelajak uchun tajriba.',image:history,url:'https://edusat-uz-tarix.vercel.app',topics:['Qadimgi dunyo','Buyuk ipak yo‘li','O‘zbekiston tarixi'],lesson:'Buyuk ipak yo‘li Sharq va G‘arbni bog‘lagan savdo yo‘llari tarmog‘i edi. U orqali ipak, ziravorlar va hunarmandchilik mahsulotlari bilan birga ilm-fan, madaniyat va yangi g‘oyalar ham tarqalgan. Samarqand va Buxoro bu yo‘llarning muhim markazlari bo‘lgan.',question:'Buyuk ipak yo‘lining asosiy ahamiyati nimada?',answers:['Faqat harbiy yurishlar','Savdo va madaniy almashinuv','Faqat dengiz sayohatlari'],correct:1},
 {slug:'geografiya',name:'Geografiya',description:'Yer, koinot va tabiat sirlarini kashf eting.',image:geography,url:'https://edusat-uz-geografiya.vercel.app',topics:['Yer sayyorasi','Materiklar va okeanlar','Iqlim va tabiat'],lesson:'Yer o‘z o‘qi atrofida taxminan 24 soatda aylanadi. Shu harakat kun va tun almashinuvini yuzaga keltiradi. Yerning Quyosh atrofidagi aylanishi taxminan 365,25 kun davom etadi. O‘qning og‘maligi sabab yil fasllari almashinadi.',question:'Kun va tun nima sababdan almashinadi?',answers:['Yer o‘z o‘qi atrofida aylanadi','Oy Yer atrofida aylanadi','Quyosh soviydi'],correct:0},
 {slug:'tibbiyot',name:'Tibbiyot anatomiyasi',description:'Inson tanasi va sog‘lom hayot asoslari.',image:medicine,url:'https://edusat-uz-tibbiyot-anatomiya.vercel.app',topics:['Yurak va qon aylanishi','Nafas olish tizimi','Skelet va mushaklar'],lesson:'Inson yuragi to‘rtta kameradan iborat: ikkita bo‘lmacha va ikkita qorincha. Yurakning o‘ng tomoni qonni o‘pkaga, chap tomoni esa kislorodga boy qonni tanaga haydaydi. Qon tomirlari arteriyalar, venalar va kapillyarlarga bo‘linadi.',question:'Inson yuragida nechta kamera bor?',answers:['Ikki','Uch','To‘rt'],correct:2},
 {slug:'biologiya',name:'Biologiya / Anatomiya',description:'Tabiat qonunlari va hayot jarayonlari.',image:biology,url:'https://edusat-uz-biologiya.vercel.app/uz',topics:['Hujayra tuzilishi','DNK va genetika','Inson anatomiyasi'],lesson:'Hujayra tirik organizmlarning asosiy tuzilish va faoliyat birligidir. DNK irsiy axborotni saqlaydi. O‘simlik hujayralaridagi xloroplastlar fotosintez jarayonida yorug‘lik energiyasidan foydalanib organik moddalar hosil qiladi.',question:'Irsiy axborotni qaysi molekula saqlaydi?',answers:['Suv','DNK','Kislorod'],correct:1},
 {slug:'matematika',name:'Matematika',description:'Hisoblash, mantiq va tahlil san’ati.',image:math,url:'https://edusat-matematika.vercel.app',topics:['Algebra','Geometriya','Funksiyalar'],lesson:'Kvadrat tenglama ax² + bx + c = 0 ko‘rinishida yoziladi, bunda a nolga teng emas. Diskriminant D = b² − 4ac. D musbat bo‘lsa, ikki haqiqiy ildiz; nol bo‘lsa, bitta takroriy ildiz mavjud. Masalan, x² − 5x + 6 = 0 tenglamaning ildizlari 2 va 3.',question:'x² − 5x + 6 = 0 tenglamaning ildizlari?',answers:['1 va 6','2 va 3','−2 va −3'],correct:1},
 {slug:'ingliz-tili',name:'Ingliz tili',description:'Dunyo bilan bog‘laning.',image:english,url:'https://edusat-english.vercel.app',topics:['Grammatika','Lug‘at','O‘qish va tushunish'],lesson:'Present Simple odatiy harakatlar va umumiy haqiqatlarni ifodalaydi. I, you, we, they bilan fe’lning asosiy shakli ishlatiladi: I learn English. He, she, it bilan fe’lga odatda -s qo‘shiladi: She learns English. So‘roq gaplarda do yoki does ishlatiladi.',question:'Qaysi gap grammatik jihatdan to‘g‘ri?',answers:['She learn English.','She learns English.','She learning English.'],correct:1},
 {slug:'rus-tili',name:'Rus tili',description:'Yangi imkoniyatlar eshigini oching.',image:russian,url:'https://edusat-rustili.vercel.app',topics:['Alifbo','Grammatika','Kundalik muloqot'],lesson:'Rus alifbosida 33 ta harf bor. «Здравствуйте» — rasmiy salomlashish, «Привет» — norasmiy salomlashish. «Спасибо» rahmat, «Пожалуйста» esa iltimos yoki marhamat ma’nosida ishlatiladi.',question:'«Спасибо» so‘zining ma’nosi nima?',answers:['Salom','Xayr','Rahmat'],correct:2},
 {slug:'kimyo',name:'Kimyo',description:'Moddalar va ularning xossalari.',image:chemistry,url:'https://edusat-kimyo.vercel.app',topics:['Atom tuzilishi','Kimyoviy bog‘lanish','Reaksiyalar'],lesson:'Atom yadrosi proton va neytronlardan tashkil topgan. Elektronlar yadro atrofida joylashadi. Elementning atom raqami uning protonlari soniga teng. Suv molekulasi H₂O ikkita vodorod va bitta kislorod atomidan iborat.',question:'H₂O molekulasida nechta vodorod atomi bor?',answers:['Bitta','Ikkita','Uchta'],correct:1},
];
export type Subject = typeof subjects[number];
export function pageHead(title:string,description:string) { return {meta:[{title:`${title} — ASTRA`},{name:'description',content:description},{property:'og:title',content:`${title} — ASTRA`},{property:'og:description',content:description},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}; }