import { createFileRoute, Link } from '@tanstack/react-router';
import { BookOpen, Search, ArrowLeft } from 'lucide-react';
import { subjects, pageHead } from '@/lib/subjects';
import { SubjectCard } from '@/components/subject-card';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
export const Route=createFileRoute('/fanlar')({validateSearch:(search:Record<string,unknown>):{q?:string|undefined;mode?:string|undefined}=>({q:typeof search['q']==='string'?search['q']:undefined,mode:typeof search['mode']==='string'?search['mode']:undefined}),head:()=>pageHead('Fanlar','ASTRA fanlar olami: sakkizta yo‘nalish, kirish darslari va bilim testlari.'),component:SubjectsPage});
function SubjectsPage(){const search=Route.useSearch();const [query,setQuery]=useState(search['q']??'');const titles:Record<string,string>={darslar:'Darslar',testlar:'Testlar',modellar:'3D modellar',saqlanganlar:'Saqlanganlar'};const title=search['mode']?titles[search['mode']]??'Fanlar':'Fanlar';let found=subjects.filter(s=>s.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()));if(search['mode']==='saqlanganlar')found=[];
 return <div className="content-page"><Link to="/" className="back-link"><ArrowLeft/> Bosh sahifa</Link><div className="page-heading"><span className="eyebrow">ASTRA / BILIM OLAMI</span><h1>{title}</h1><p>{search['mode']==='modellar'?'Fan sahifasidan “To‘liq saytga o‘tish” orqali tashqi platformadagi modellarni oching.':'O‘zingizga qiziq bo‘lgan yo‘nalishni tanlang.'}</p></div><div className="filter-bar"><span><BookOpen/> {found.length} ta fan</span><label className="search-box"><Search/><input aria-label="Fanlar orasidan qidirish" placeholder="Fan qidirish…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="catalog-grid">{found.map(s=><SubjectCard key={s.slug} subject={s}/>)}</div>{!found.length&&<div className="empty-state"><BookOpen/><h2>{search['mode']==='saqlanganlar'?'Hali saqlangan fanlar yo‘q':'Fan topilmadi'}</h2><p>{search['mode']==='saqlanganlar'?'Hozircha fanlarni to‘plamga saqlash mavjud emas.':'Boshqa nom bilan qidirib ko‘ring.'}</p><Button variant="cosmic" asChild><Link to="/fanlar" search={{q:undefined,mode:undefined}}>Barcha fanlar <ArrowLeft/></Link></Button></div>}</div>;
}